#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin/X11:/usr/local/bin

pid=$(ps | grep [a]ppname | awk '{print $1}')

if [ ! -z "$pid" ]
then
     echo "Kill application"
     kill "$pid"
fi
